In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.6/site-packages/numpy/__init__.py'>

# Create

In [4]:
# from python array
arr = np.array([0, 1, 2, 3, 4, 5])
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
arr = np.array([[0,1,2],[3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
# using range function
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.array([range(5), range(5,10)])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# using zeros
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# using ones
arr = np.ones((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# using identity
arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# using arange
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])


# Access

In [14]:
# all
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# one element
arr[2,1]

0.0

In [23]:
# slicinig
# works like a pointer
b = arr[1:3, 1:3]
b

array([[1., 0.],
       [0., 3.]])

In [28]:
arr[-2:, -2:]

array([[1., 0.],
       [0., 1.]])

# Broadcasting

In [30]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [33]:
x.shape

(6,)

In [35]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [36]:
y.shape

(5,)

In [37]:
x + y

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [39]:
# using reshape
xx = x.reshape(6,1)
xx

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
z= xx + y
z

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.]])

In [46]:
z.shape

(6, 5)

In [47]:
p = np.ones(2)

In [48]:
p

array([1., 1.])

In [49]:
xx + p

array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.],
       [6., 6.]])

# Calculations

In [51]:
# add
arr1 = np.ones((3,3))
arr2 = np.arange(9).reshape(3,3)
arr1 + arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [53]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr1 + 1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [55]:
np.sum(arr1)

9.0

In [56]:
(arr1 + 1) * arr2

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.]])

In [59]:
# multiply of matrix
np.dot(arr1, arr2)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [61]:
arr1 = np.ones((5,2))
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
arr2 = np.arange(10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
# concatenate
# will create new array
np.concatenate((arr1, arr2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [97]:
np.concatenate((arr1, arr2), axis=1)

array([[1., 1., 0., 1.],
       [1., 1., 2., 3.],
       [1., 1., 4., 5.],
       [1., 1., 6., 7.],
       [1., 1., 8., 9.]])

In [98]:
# split
arr3 = np.concatenate((arr1, arr2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [99]:
r1, r2 = np.split(arr3, 2)

In [100]:
r1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [101]:
r2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [113]:
h1, h2 = np.hsplit(arr3, 2)

In [114]:
h1

array([[5.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [4.],
       [6.],
       [8.]])

In [116]:
# delete
# will create new pointer
arr3

array([[5., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [117]:
np.delete(arr3, 0, axis=0)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [118]:
arr3

array([[5., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [119]:
np.delete(arr3, 1, axis=1)

array([[5.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [2.],
       [4.],
       [6.],
       [8.]])

In [120]:
arr3

array([[5., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [140]:
# transpose
# transpose returns pointer
# can assign new value
np.transpose(arr3)

array([[4., 1., 1., 1., 1., 0., 2., 4., 6., 8.],
       [1., 1., 1., 1., 1., 1., 3., 5., 7., 9.]])

In [141]:
arr3

array([[4., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [146]:
# diagonal
# create readonly pointer
da = arr3.diagonal()
da

array([4., 1.])

# Mask

In [170]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [171]:
# operation create a new array
m = arr > 2
m

array([False, False, False,  True,  True])

In [172]:
type(m)

numpy.ndarray

In [178]:
# nparray subscript with mask
# will create a new array
ma = arr[m]
ma

array([4, 4])

In [182]:
# complex mask
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
m = ((arr < 4) | (arr > 7))

In [188]:
m

array([ True,  True,  True,  True, False, False, False, False,  True,
        True])

In [189]:
arr[m]

array([0, 1, 2, 3, 8, 9])