In [1]:
from numpy.random import randn
import numpy as np

# 2차원에 대한 데이터 가공 방식은?

In [4]:
# 랜덤으로 데이터를 만들고 싶다면?
data = randn(2, 3)
data

array([[-0.60721488,  0.59273408,  2.043906  ],
       [ 2.45597519, -0.21931897,  0.93053176]])

In [5]:
# 각 데이터의 타입을 알고 싶다면?
data.dtype

dtype('float64')

In [6]:
# 각 배열끼리 연산하는 방법은?
# 모양이 같다면?
data + data

array([[-1.21442977,  1.18546816,  4.087812  ],
       [ 4.91195038, -0.43863795,  1.86106351]])

In [7]:
# 모양이 다르다면?
data + 5

array([[4.39278512, 5.59273408, 7.043906  ],
       [7.45597519, 4.78068103, 5.93053176]])

In [9]:
# 모양을 알고 싶다면?
data.shape

(2, 3)

In [12]:
# 차원을 알고 싶다면?
data.ndim

2

In [11]:
# numpy 생성하는 방법은?
# 기존 list에서
from_list = np.array([1,2,3])
from_list

array([1, 2, 3])

In [14]:
# 0으로만 만들기
zeros = np.zeros(10,)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# 초기화는 하지 않고 모양만 만든다.
# 예전에는 많은 데이터를 다룰 때 속도 측면에서 유리함.
np.empty((2,3,4))

array([[[6.89919491e-310, 4.66054973e-310, 8.10267659e-322,
         6.89910995e-310],
        [2.78176672e-309, 5.59442346e-313, 4.23155903e-314,
         7.29200510e-304],
        [7.29200510e-304, 6.05278080e-310, 2.71615720e-312,
                     nan]],

       [[1.46059092e-309, 1.86735664e-312, 6.94848008e+140,
         2.85922534e-306],
        [1.39084092e-309, 2.78151225e-309, 5.56285457e-309,
         4.17222568e-309],
        [4.01256357e-315, 2.71615720e-312,             nan,
         1.46093044e-309]]])

In [18]:
# 순서 값 채우려면?
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 만들면서 데이터 타입도 지정해 주려면?
sample = np.array([1,2,3,4], dtype=np.float64)

In [25]:
# 데이터 타입을 바꾸고 싶다면?
int_sample = sample.astype(np.int64)
int_sample

array([1, 2, 3, 4])

In [27]:
# 만약에 2데이터 형식을 동일하게 하고 싶다면?
#a.astype(b.dtype)

In [28]:
# 어떤 연산을 할 수 있는가?
# + * / ** 


In [41]:
# 슬라이싱한 것의 결과에 할당을 하고 싶다면?
# 복사를 해두려면?
old_data = data.copy()
print(old_data)

data[:][1] = 3
data

[[2. 2. 2.]
 [3. 3. 3.]]


array([[2., 2., 2.],
       [3., 3., 3.]])

In [48]:
data

array([[2., 2., 2.],
       [3., 3., 3.]])

In [53]:
data.shape

(2, 3)

In [49]:
data.ndim

2

In [50]:
data[1].ndim

1

In [51]:
data[1].shape

(3,)

In [54]:
# 조건에 맞는 데이터만 가져오고 싶으면?
names = np.array(['Bob', 'John', 'Bob', 'Will'])
names

array(['Bob', 'John', 'Bob', 'Will'], dtype='<U4')

In [57]:
mask = names == 'Bob'
mask

array([ True, False,  True, False])

In [60]:
# nparray[nparray]
names[mask]

array(['Bob', 'Bob'], dtype='<U4')

In [65]:
# fancy indexing
# 인덱스 정보로 선택해서 뿌려주고 싶다면? 원하는 대로 배치하려면?
arr = np.empty(28).reshape(7,4)

for i in range(7):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [67]:
arr[[3,0],[1,2]]

array([3., 0.])

In [72]:
# 가져오고 똑 
# arr[...][....]
# np.ix_([], [])

`

In [75]:
# 행렬 계산을 하고 싶으면?
#  T
# np.dot(a.T, b)

# 형태를 바꾸고 싶으면?
# transpose([axis,axis,axis])
# swapaxes(1,2)

In [1]:
# 열 기준으로 값을 쭉 넣고싶다?
# np.insert

In [3]:
%whos

Interactive namespace is empty.
