# 문서를 어떻게 표현할 수 있을까?

## 문서에 있는 용어를 기준으로 문서를 표현해 보자 (Term-Document Matrix, TDM)

[문제점]
대부분의 문서에는 자주 나오는 단어가 있기 때문에 모두 유사해 보인다.
마치 사람이 모두 팔다리, 눈코입이 유사하니 다 유사해 보이는 것과 같다.

## TDM 문제를 해결하고 공통된 특징을 약화시켜서 차이를 잘 드러나게 하려면? 
### (Term Frequency-Inverse Document Frequency, TF-IDF)

idf: 얼마나 특이한가 (logN - log(1 + df(t))

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

tfidfv = TfidfVectorizer().fit(corpus)
tfidfv

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [6]:
tfidfv.transform(corpus).toarray()

array([[0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
        0.46735098, 0.        , 0.35543247, 0.46735098],
       [0.        , 0.        , 0.79596054, 0.        , 0.        ,
        0.        , 0.        , 0.60534851, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.57735027, 0.        , 0.        ]])

In [7]:
tfidfv.vocabulary_

{'you': 7,
 'know': 1,
 'want': 5,
 'your': 8,
 'love': 3,
 'like': 2,
 'what': 6,
 'should': 4,
 'do': 0}

In [10]:
tfidfv.transform(corpus).toarray()[0]

array([0.        , 0.46735098, 0.        , 0.46735098, 0.        ,
       0.46735098, 0.        , 0.35543247, 0.46735098])

In [11]:
tfidfv.transform(corpus).toarray()[1]

array([0.        , 0.        , 0.79596054, 0.        , 0.        ,
       0.        , 0.        , 0.60534851, 0.        ])